name = "avatar-upload"
main = "src/index.ts"
compatibility_date = "2022-07-31"

node_compat = true

[vars]
BASE_WEB3_ENDPOINT = "https://web3.ens.domains/v1"
SUPPORTED_NETWORKS = ["mainnet", "goerli", "ropsten"]
REGISTRY_ADDRESS = "0x00000000000c2e074ec69a0dfb2997ba6c7d2e1e"
WRAPPER_ADDRESS = '{ "mainnet": "", "goerli": "0x060f1546642E67c485D56248201feA2f9AB1803C", "ropsten": "0xF82155e2a43Be0871821E9654Fc8Ae894FB8307C" }'
MULTICALL_ADDRESS = "0xcA11bde05977b3631167028862bE2a173976CA11"
BASE_REGISTRAR_ADDRESS = "0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85"

[[r2_buckets]]
binding = "AVATAR_BUCKET"
bucket_name = 'avatar-storage'
preview_bucket_name = 'preview-avatar-storage'